### ISSUE TITLE
05 - high order functions/solution_2.hs에 finalPosition 함수 에러

### ISSUE THREAD

**Issue by plzfday** [jwvg0425/HaskellStudy#1]
안녕하세요. 만드신 자료 보면서 하스켈을 배우고 있습니다. 귀중한 자료 만들어 주셔서 감사합니다.  
study 5 - higher order function의 연습문제를 풀다가 정답 코드에 문제가 있는 것 같아서 이슈 남깁니다.  

코드를 그대로 복사해서 제 환경에서 돌리면 컴파일러 에러가 나는데 함수 타입을 정해주니 문제가 해결됐습니다.
```haskell
finalPosition :: (Num a) => (a, a) -> [(a, a)] -> (a, a)
finalPosition = foldl (\(x,y) (dx,dy) -> (x+dx, y+dy))
```
아니면 제가 처음에 생각했던 코드도 정답이 될 수 있을 것 같습니다. 물론 정답 코드와 비교하면 장황한 느낌이 있긴 합니다.
```haskell
finalPosition' (x0, y0) coords = let (dX, dY) = foldl1 (\(x, y) (dx, dy) -> (x + dx, y + dy)) coords in (x0 + dX, y0 + dY)
```

하스켈 타입 추론이 항상 만능은 아니네요! 맘 편하려면 함수 만들 때마다 타입을 직접 지정해주는 게 나을 것 같습니다 😀

**Comment by jwvg0425** [comment]
해당 함수만 써놓으면 에러가 나지만,

```haskell
finalPosition = foldl (\(x,y) (dx,dy) -> (x+dx, y+dy))
ans = finalPosition (3,5) [(1,1), (-1,2), (2,4)]
```

등과 같이 실제 함수를 사용하는 부분이 있으면 컴파일 에러가 나지 않을거에요. finalPosition 함수만 있을 경우 타입을 결정할 수 없는데 그걸 실제로 사용하는 부분이 있으면 적용된 인자에 맞춰서 타입을 추론할 수 있기 때문입니다.

물론 이와 별개로 함수의 타입은 되도록 적어주는게 좋은 습관이기도 합니다.

**Comment by jwvg0425** [comment]
추가적으로, 작성하신 finalPositon' 의 경우는 empty list가 인자로 들어오는 경우 예외가 발생하는 문제가 있어서 바람직하지는 않습니다. `finalPosition (2,3) [] = (2,3)` 이 반환되는게 의미상 맞겠지요.

**Comment by jwvg0425** [comment]
부연 설명을 좀 하자면,
현재 `finalPosition coords = foldl (\(x,y) (dx,dy) -> (x+dx, y+dy)) coords` 식으로 point-free 방식을 사용하지 않을 경우 정상적으로 컴파일이 되는데 coords를 생략하면 컴파일이 안 됩니다. 저도 좀 헷갈려서 찾아봤는데, 제가 처음 이 코드를 작성할 당시에는 저 소스 코드만으로도 잘 작동을 했어요. 그 때는 foldl 함수의 타입이 `foldl :: (a -> b -> a) -> a -> [b] -> a` 였는데, 지금은 타입 시그니쳐가 바뀌어서 `foldl`이 `Foldable`이라는 타입 클래스의 함수로 변경되었습니다. 즉, `foldl :: (Foldable t) => (b -> a -> b) -> b -> t a -> b` 가 됐어요. 이렇게 되면서 생략된 인자가 리스트라는 가정을 할 수 있었던게 해당 가정을 할 수 없게 되면서 컴파일 에러가 나게 된 것 같습니다. coords 인자를 빼면 `t a` 부분이 생략되면서 `finalPosition`의 시그니쳐만 보고는 `t` 타입을 추론할 수 있는 방법이 없어지는데 여기에 컴파일러가 마음대로 제약을 걸지 못하기 때문에 에러가 발생하는것 같아요.

**Comment by plzfday** [comment]
설명 감사합니다. 제가 짠 코드에 대한 리뷰도 감사합니다. 많은 자료 (저희 학교 자료에서도)에서 Foldable 클래스에 대한 설명을 들은 적이 없어서 foldl 타입이 ghc 버전이 업그레이드 되면서 바뀌었구나 어림잡고 있었는데 그게 맞는 거였네요.

다시 한번 귀중한 자료 만들어 주셔서 감사합니다 :)
