### ISSUE TITLE
typeof

### ISSUE THREAD

**Issue by gosunman** [jwvg0425/HaskellStudy#3]
https://www.slideshare.net/namhyeonuk90/haskell-study-3

18쪽에

fromIntegral의 타입 서명이 잘못나와 있습니다.

as-is `(Num b, Integral a) => a -> b`
to-be `(Integral b, Num a) => a -> b`

좋은 자료 만들어주셔서 항상 감사합니다!

**Comment by jwvg0425** [comment]
http://zvon.org/other/haskell/Outputprelude/fromIntegral_f.html

오류 없습니다. fromIntegral 함수는 Integral에 해당하는 타입을 Num에 해당하는 타입으로 바꿔서 정수형 값을 정수형이 아닌 값과 연산할 수 있게 만들어주는 함수입니다.
